# Generated by Django 5.1 on 2024-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish"]},
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="default", max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
