# Generated by Django 5.1 on 2024-08-20 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_category_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A label for name tag.", max_length=31, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A label for URL config.", max_length=31, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "tags for posts",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish"],
                "verbose_name": "Публікація",
                "verbose_name_plural": "Публікації",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="blog_posts", to="blog.tag"),
        ),
    ]
