# Generated by Django 5.1 on 2024-08-28 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_tag_options_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
