# Generated by Django 5.1 on 2024-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_rating_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveIntegerField(),
        ),
    ]
