# Generated by Django 5.0.7 on 2024-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_category_alter_tag_options_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.png", upload_to="post/images/"),
            preserve_default=False,
        ),
    ]
